---
- name: Append SSH public key to authorized_keys on target servers
  hosts: your_target_servers  # Replace with your target server group or host pattern
  gather_facts: true
  tasks:
    - name: Take authorized_keys backup on target server
      command: >
        sh -c 'cp /home/{{ ansible_user }}/.ssh/authorized_keys /home/{{ ansible_user }}/.ssh/authorized_keys-$(date +%Y%m%d%H%M%S).bak'
      delegate_to: "{{ inventory_hostname }}"
      tags: rename_authorized_keys

    - name: Read local SSH public key
      ansible.builtin.slurp:
        src: /home/{{ ansible_user }}/sshkeys/id_rsa.pub
      register: ssh_key_file
      delegate_to: localhost

    - name: Append SSH public key to authorized_keys
      ansible.builtin.lineinfile:
        dest: /home/{{ ansible_user }}/.ssh/authorized_keys
        line: "{{ ssh_key_file.content | b64decode }}"
        create: yes
      delegate_to: "{{ inventory_hostname }}"
