---
- name: Search in Splunk and export to CSV
  hosts: localhost
  gather_facts: False

  vars_prompt:
    - name: query
      prompt: "Enter the search query"
    - name: earliest_time
      prompt: "Enter the earliest time (in Splunk time format)"
    - name: latest_time
      prompt: "Enter the latest time (in Splunk time format)"
    - name: output_file
      prompt: "Enter the output CSV file path"

  tasks:
    - name: Authenticate with Splunk
      uri:
        url: "https://splunk_server:8089/services/auth/login"
        method: POST
        body_format: form-urlencoded
        body:
          username: "{{ splunk_username }}"
          password: "{{ splunk_password }}"
      register: login_response
      no_log: true

    - name: Extract session key
      set_fact:
        session_key: "{{ login_response.content | b64decode | xmldom | xpath('/response/sessionKey/text()') | first }}"

    - name: Perform search in Splunk
      uri:
        url: "https://splunk_server:8089/services/search/jobs/export"
        method: POST
        headers:
          Authorization: "Splunk {{ session_key }}"
        body_format: form-urlencoded
        body:
          search: "{{ query }}"
          earliest_time: "{{ earliest_time }}"
          latest_time: "{{ latest_time }}"
          output_mode: "csv"
        dest: "{{ output_file }}"

  vars_files:
    - credentials.yml
