---
- name: Update authorized_keys file
  hosts: servera
  become: yes
  become_user: student  # Replace with the actual SSH user
  vars:
    specified_strings:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGtUW3is"
      - "mHyuCW4CDdTVOOOq6aySdtYenXFWWx7HJa4V"
  tasks:
    - name: Read the current authorized_keys file
      shell: cat /home/student/.ssh/authorized_keys
      register: current_authorized_keys
      check_mode: no

    - name: Create updated authorized_keys content
      set_fact:
        updated_authorized_keys: "{{ current_authorized_keys.stdout_lines }}"
      check_mode: no

    - name: Add # to lines with specified strings
      loop: "{{ specified_strings }}"
      loop_control:
        loop_var: specified_string
      set_fact:
        updated_authorized_keys: "{{ updated_authorized_keys | map('regex_replace', '^(' + specified_string + ')', '# \\1') }}"
      check_mode: no

    - name: Update authorized_keys file
      copy:
        content: "{{ updated_authorized_keys | join('\n') }}"
        dest: /home/student/.ssh/authorized_keys
      check_mode: no
